# Generated by Django 5.2.5 on 2025-08-10 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='seed_images/')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='seed_images/annotated/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeedMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_number', models.PositiveIntegerField()),
                ('width_mm', models.FloatField()),
                ('height_mm', models.FloatField()),
                ('seed_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measure.seedimage')),
            ],
        ),
    ]
